### ISSUE TITLE
 [Bug] Kickbot stops working after so long since latest update

### ISSUE THREAD

**Issue by SendMemesPlox** [Sehelitar/Kick.bot#50] opened 2024-03-17 16:26 UTC
Since the latest update to Kickbot I've been having problems with just general commands that worked before this update.
No matter how many times I've uninstalled/reinstall it doesn't matter.

**Comment by Jyojibh** [comment] 2024-03-17 16:42
+1

**Comment by Sehelitar** [comment] 2024-03-18 20:18
Hi!
A log file would be more than welcome 🙏
When something wrong happens, there is 99% chance something helpful will be written in it.
Thank you!

**Comment by GzusJankins1** [comment] 2024-03-19 00:52
[log_20240318.log](https://github.com/Sehelitar/Kick.bot/files/14643889/log_20240318.log)
heres a log file im having same issue the extention is crashing streamerbot

**Comment by Jyojibh** [comment] 2024-03-19 07:03
[log_20240316.log](https://github.com/Sehelitar/Kick.bot/files/14646747/log_20240316.log)

Log file for my issues.

**Comment by gzusjankins** [comment] 2024-03-19 11:46
Fingers crossed on the fix for this because this extention has made my whole year !

**Comment by Jyojibh** [comment] 2024-03-19 12:23
> Fingers crossed on the fix for this because this extention has made my whole year !

100% I've always used Streamer.Bot for Twitch and using this for Kick has been amazing! Done so many cool things with it!

**Comment by gzusjankins** [comment] 2024-03-19 12:29
Same for me i have automated host scenes setup as well as many other things its such a great app to use !

**Comment by Sehelitar** [comment] 2024-03-19 13:04
Ok, so according to your logs, the issue is the same.
The bad news is the problem is located within LiteDB (this is a [known issue](https://github.com/mbdavid/LiteDB/issues/2442)) which is a Streamer.bot component I can't update/modify whithout breaking the bot itself.
The good news is that I should be able to work around this and prevent this error to crash the entire module.
I'll look into it ASAP !

**Comment by Jyojibh** [comment] 2024-03-19 13:14
I appreciate you working on this so fast! and how amazing your support has been!

**Comment by GzusJankins1** [comment] 2024-03-20 20:06
@Sehelitar any update on this ?

**Comment by Sehelitar** [comment] 2024-03-21 20:31
I couldn't reproduce this problem on my machine, so I tried to implement a fix based on your logs.
I made a beta update to test this fix, along with a few other modifications.
More details and download link here : https://github.com/Sehelitar/Kick.bot/releases/tag/v0.4.0-beta.1

**Comment by Jyojibh** [comment] 2024-03-21 21:27
So after a bit of "Testing" We seem to have been able to break it again, It does the same thing after so long of using things it sort of just stops working.

This is with the new v-0.4.0-beta.1 Log file below.

[log_20240321.log](https://github.com/Sehelitar/Kick.bot/files/14709917/log_20240321.log)

**Comment by Sehelitar** [comment] 2024-03-21 22:24
I made a new beta : https://github.com/Sehelitar/Kick.bot/releases/download/v0.4.0-beta.1/Kick.bot-v0.4.0-beta.2.zip
I bubble-wrapped everything. It won't solve the root problem but should prevent complete crashes of the bot.
This is a temporary fix while I'm working on a better solution.

I want to thank you for your patience and understanding, I know this kind of thing can be frustrating, but I'm confident this is fixable. 🙏

**Comment by Jyojibh** [comment] 2024-03-21 22:34
> I made a new beta : https://github.com/Sehelitar/Kick.bot/releases/download/v0.4.0-beta.1/Kick.bot-v0.4.0-beta.2.zip I bubble-wrapped everything. It won't solve the root problem but should prevent complete crashes of the bot. This is a temporary fix while I'm working on a better solution.
> 
> I want to thank you for your patience and understanding, I know this kind of thing can be frustrating, but I'm confident this is fixable. 🙏

I truly appreciate you always being so awesome and helpful to the Kick Community! We all just want something that works so we all put in that effort to improve and fix things! So im always happy to help the community and yourself.

Thank you again, I will check things out and see how it goes.

**Comment by Jyojibh** [comment] 2024-03-21 22:49
So been testing again and unfortunately it did hold up much longer, and it did work as intended but after I minimised it I got the windows sound to say it crashed. 

Hopefully we can get to the bottom of this! Or the new fix works 😅 Do we know if the Lite DB issue will be solved any time soon? 

[log_20240321.log](https://github.com/Sehelitar/Kick.bot/files/14712006/log_20240321.log)

**Comment by Sehelitar** [comment] 2024-03-21 23:05
The more I read about LiteDB, the more I hate it 😂
The bubble-wrap worked. So naturally LiteDB found a new way to crash in its own code so I can't fix it there. 🤡

I need some time to properly fix this (and maybe get rid of LiteDB...). In the meantime, if you need a stable bot, I recommend a rollback to SB 0.2.2 (a backup should be available in the bot's folder) until this is fixed.

**Comment by gzusjankins** [comment] 2024-03-22 10:54
> The more I read about LiteDB, the more I hate it 😂 The bubble-wrap worked. So naturally LiteDB found a new way to crash in its own code so I can't fix it there. 🤡
> 
> I need some time to properly fix this (and maybe get rid of LiteDB...). In the meantime, if you need a stable bot, I recommend a rollback to SB 0.2.2 (a backup should be available in the bot's folder) until this is fixed.

Thank you for your work this is great. My wuestion is if i roll back to sb 0.2.2 can i still use the kickbot ? Right bot i can trigger things manually after it crashes ? Im excited for the fix and thank you so much for even making this possible your amazing !

**Comment by Jyojibh** [comment] 2024-03-22 13:29
> > > > The more I read about LiteDB, the more I hate it 😂 The bubble-wrap worked. So naturally LiteDB found a new way to crash in its own code so I can't fix it there. 🤡
> > > > I need some time to properly fix this (and maybe get rid of LiteDB...). In the meantime, if you need a stable bot, I recommend a rollback to SB 0.2.2 (a backup should be available in the bot's folder) until this is fixed.
> > > 
> > > 
> > > Thank you for your work this is great. My wuestion is if i roll back to sb 0.2.2 can i still use the kickbot ? Right bot i can trigger things manually after it crashes ? Im excited for the fix and thank you so much for even making this possible your amazing !
> > 
> > 
> > Hey Jankins,
> > If you roll back to SB 0.2.2 And then use the [https://github.com/Sehelitar/Kick.bot/releases/tag/v0.3.11](url) Thats all working for me and works really well still! Haven't had any crash outs or anything yet! So would recommend using that for now!
> 
> What features does that version have all the same ?

The features that are missing are.

Which was introduced in the latest versions for SB 0.2.3

https://github.com/Sehelitar/Kick.bot/issues/39 Updated [Chat Message Deleted](https://github.com/Sehelitar/Kick.bot/wiki/Triggers#chat-message-deleted) trigger with new message arguments added (when available).
https://github.com/Sehelitar/Kick.bot/issues/40 New [User Unbanned](https://github.com/Sehelitar/Kick.bot/wiki/Triggers#user-unbanned) trigger.
 https://github.com/Sehelitar/Kick.bot/issues/42 New [GetClipMP4URL](https://github.com/Sehelitar/Kick.bot/wiki/Methods#getclipmp4url) method.
 https://github.com/Sehelitar/Kick.bot/issues/49 New [GetChannelCounters](https://github.com/Sehelitar/Kick.bot/wiki/Methods#getchannelcounters) method to get your followers and viewers counters.

**Comment by gzusjankins** [comment] 2024-03-22 13:40
> > > > > The more I read about LiteDB, the more I hate it 😂 The bubble-wrap worked. So naturally LiteDB found a new way to crash in its own code so I can't fix it there. 🤡
> > > > > I need some time to properly fix this (and maybe get rid of LiteDB...). In the meantime, if you need a stable bot, I recommend a rollback to SB 0.2.2 (a backup should be available in the bot's folder) until this is fixed.
> > > > 
> > > > 
> > > > Thank you for your work this is great. My wuestion is if i roll back to sb 0.2.2 can i still use the kickbot ? Right bot i can trigger things manually after it crashes ? Im excited for the fix and thank you so much for even making this possible your amazing !
> > > 
> > > 
> > > Hey Jankins,
> > > If you roll back to SB 0.2.2 And then use the [https://github.com/Sehelitar/Kick.bot/releases/tag/v0.3.11](url) Thats all working for me and works really well still! Haven't had any crash outs or anything yet! So would recommend using that for now!
> > 
> > 
> > What features does that version have all the same ?
> 
> The features that are missing are.
> 
> Which was introduced in the latest versions for SB 0.2.3
> 
> #39 Updated [Chat Message Deleted](https://github.com/Sehelitar/Kick.bot/wiki/Triggers#chat-message-deleted) trigger with new message arguments added (when available). #40 New [User Unbanned](https://github.com/Sehelitar/Kick.bot/wiki/Triggers#user-unbanned) trigger. #42 New [GetClipMP4URL](https://github.com/Sehelitar/Kick.bot/wiki/Methods#getclipmp4url) method. #49 New [GetChannelCounters](https://github.com/Sehelitar/Kick.bot/wiki/Methods#getchannelcounters) method to get your followers and viewers counters.

Ok awesome thank you do i need to delete the current version of the kickbot in sb ?

**Comment by Jyojibh** [comment] 2024-03-22 16:09
You can literally just download it, Copy the files directly over the SB files and overwrite the files from 0.2.2 onto the current folder and you should be good to go

**Comment by GzusJankins1** [comment] 2024-03-22 18:59
> You can literally just download it, Copy the files directly over the SB files and overwrite the files from 0.2.2 onto the current folder and you should be good to go

the link you provided https://github.com/Sehelitar/Kick.bot/issues/urlgives me an error was the versions the latest version? cause thats the only version i have

**Comment by Sehelitar** [comment] 2024-03-23 15:21
I did my best to replicate the conditions that lead to the exact problem you encountered, without success.
So I tried a different approach to fix it but I can't properly test it on my end 😢 
If an adventurous mind wants to test it, it's available here : 
https://github.com/Sehelitar/Kick.bot/releases/download/v0.4.0-beta.1/Kick.bot-v0.4.0-beta.3.zip
I'll keep my fingers crossed 🤞

**Comment by Jyojibh** [comment] 2024-03-23 16:26
> I did my best to replicate the conditions that lead to the exact problem you encountered, without success. So I tried a different approach to fix it but I can't properly test it on my end 😢 If an adventurous mind wants to test it, it's available here : https://github.com/Sehelitar/Kick.bot/releases/download/v0.4.0-beta.1/Kick.bot-v0.4.0-beta.3.zip I'll keep my fingers crossed 🤞

So as someone that loves diving into things head first and to help test for the community! This has fixed the issue! I upgraded, Upgraded to the latest version and everything works as intended!

**Comment by Sehelitar** [comment] 2024-03-23 18:01
> > I did my best to replicate the conditions that lead to the exact problem you encountered, without success. So I tried a different approach to fix it but I can't properly test it on my end 😢 If an adventurous mind wants to test it, it's available here : https://github.com/Sehelitar/Kick.bot/releases/download/v0.4.0-beta.1/Kick.bot-v0.4.0-beta.3.zip I'll keep my fingers crossed 🤞
> 
> So as someone that loves diving into things head first and to help test for the community! This has fixed the issue! I upgraded, Upgraded to the latest version and everything works as intended!

And I thank you for the invaluable help you're providing in testing all of this, for your ideas and insights and your bugs reports.  This is greatly appreciated. 🙏 
If everything is working fine, I'll release the final 0.4.0 version in the next 24h.

**Comment by Jyojibh** [comment] 2024-03-23 18:18
> > > I did my best to replicate the conditions that lead to the exact problem you encountered, without success. So I tried a different approach to fix it but I can't properly test it on my end 😢 If an adventurous mind wants to test it, it's available here : https://github.com/Sehelitar/Kick.bot/releases/download/v0.4.0-beta.1/Kick.bot-v0.4.0-beta.3.zip I'll keep my fingers crossed 🤞
> > 
> > 
> > So as someone that loves diving into things head first and to help test for the community! This has fixed the issue! I upgraded, Upgraded to the latest version and everything works as intended!
> 
> And I thank you for the invaluable help you're providing in testing all of this, for your ideas and insights and your bugs reports. This is greatly appreciated. 🙏 If everything is working fine, I'll release the final 0.4.0 version in the next 24h.

Will this be the exact same as the beta or should i upgrade once again ?

**Comment by Sehelitar** [comment] 2024-03-23 18:32
If everything is working fine as it is, then no, you won't have to upgrade. The current beta will become the new stable release.

**Comment by GzusJankins1** [comment] 2024-03-23 20:38
> If everything is working fine as it is, then no, you won't have to upgrade. The current beta will become the new stable release.

also confirmed fully functional thank you so much im am BEYOND happy!!!!!!!!

**Comment by Sehelitar** [comment] 2024-03-23 20:55
v0.4.0 is now officially live 🎉  (No need to update if you already have beta.3 installed)
Thank you so much for your feedbacks and patience 🙏 Happy streaming to you all.

**Closed by Sehelitar** 2024-03-23 20:55 UTC
Labels: bug
